import Foundation

extension WordStore {
    static func sampleWords() -> [Word] {
        let entries: [(String, String, String, String, String)] = [
            ("abandon", "버리다, 포기하다", "əˈbæn.dən", "Do not abandon your plan too early.", "너의 계획을 너무 일찍 포기하지 마라."),
            ("ability", "능력", "əˈbɪl.ə.ti", "She has the ability to solve problems.", "그녀는 문제를 해결할 능력이 있다."),
            ("accept", "받아들이다", "əkˈsept", "Please accept my apology.", "제 사과를 받아 주세요."),
            ("achieve", "달성하다", "əˈtʃiːv", "You can achieve your goal with practice.", "연습하면 목표를 달성할 수 있다."),
            ("active", "활동적인", "ˈæk.tɪv", "He is active in the school club.", "그는 학교 동아리에서 활동적이다."),
            ("adapt", "적응하다", "əˈdæpt", "Students adapt to new classes quickly.", "학생들은 새 수업에 빠르게 적응한다."),
            ("advice", "조언", "ədˈvaɪs", "My teacher gave me useful advice.", "선생님이 나에게 유용한 조언을 해 주셨다."),
            ("affect", "영향을 미치다", "əˈfekt", "Weather can affect your mood.", "날씨는 기분에 영향을 줄 수 있다."),
            ("agree", "동의하다", "əˈɡriː", "I agree with your opinion.", "나는 네 의견에 동의한다."),
            ("allow", "허락하다", "əˈlaʊ", "The app allows users to study words.", "그 앱은 사용자가 단어를 공부하게 해 준다."),
            ("ancient", "고대의", "ˈeɪn.ʃənt", "We learned about ancient history.", "우리는 고대 역사에 대해 배웠다."),
            ("appear", "나타나다", "əˈpɪr", "A message will appear on the screen.", "화면에 메시지가 나타날 것이다."),
            ("arrive", "도착하다", "əˈraɪv", "They arrive at school at eight.", "그들은 8시에 학교에 도착한다."),
            ("article", "기사, 물품", "ˈɑːr.t̬ɪ.kəl", "I read an article about technology.", "나는 기술에 관한 기사를 읽었다."),
            ("attention", "주의, 관심", "əˈten.ʃən", "Pay attention to the card.", "카드에 주의를 기울여라."),
            ("available", "이용 가능한", "əˈveɪ.lə.bəl", "The file is available offline.", "그 파일은 오프라인에서도 이용 가능하다."),
            ("balance", "균형", "ˈbæl.əns", "Good habits create balance.", "좋은 습관은 균형을 만든다."),
            ("behavior", "행동", "bɪˈheɪ.vjɚ", "The button changes its behavior.", "그 버튼은 동작 방식을 바꾼다."),
            ("benefit", "이익, 혜택", "ˈben.ə.fɪt", "Review has a learning benefit.", "복습은 학습에 이점이 있다."),
            ("borrow", "빌리다", "ˈbɑːr.oʊ", "Can I borrow your notebook?", "네 공책을 빌릴 수 있을까?"),
            ("brief", "짧은", "briːf", "Write a brief sentence.", "짧은 문장을 써라."),
            ("career", "직업, 경력", "kəˈrɪr", "She wants a career in design.", "그녀는 디자인 분야의 직업을 원한다."),
            ("challenge", "도전", "ˈtʃæl.ɪndʒ", "This project is a good challenge.", "이 프로젝트는 좋은 도전이다."),
            ("choice", "선택", "tʃɔɪs", "You have a choice in the quiz.", "퀴즈에서 너에게 선택지가 있다."),
            ("common", "흔한, 공통의", "ˈkɑː.mən", "This is a common English word.", "이것은 흔한 영어 단어이다."),
            ("compare", "비교하다", "kəmˈper", "Compare the answer with the meaning.", "답을 뜻과 비교해라."),
            ("complete", "완료하다", "kəmˈpliːt", "Complete the study session.", "학습 세션을 완료해라."),
            ("connect", "연결하다", "kəˈnekt", "Connect the word and the meaning.", "단어와 뜻을 연결해라."),
            ("consider", "고려하다", "kənˈsɪd.ɚ", "Consider the example sentence.", "예문을 고려해라."),
            ("continue", "계속하다", "kənˈtɪn.juː", "Continue until all cards are done.", "모든 카드가 끝날 때까지 계속해라."),
            ("create", "만들다", "kriˈeɪt", "Create a simple word list.", "간단한 단어 목록을 만들어라."),
            ("culture", "문화", "ˈkʌl.tʃɚ", "Language and culture are connected.", "언어와 문화는 연결되어 있다."),
            ("decide", "결정하다", "dɪˈsaɪd", "Decide if you memorized the word.", "단어를 외웠는지 결정해라."),
            ("describe", "묘사하다", "dɪˈskraɪb", "Describe the word in your own words.", "그 단어를 네 말로 설명해라."),
            ("develop", "개발하다", "dɪˈvel.əp", "We develop an iOS app.", "우리는 iOS 앱을 개발한다."),
            ("difference", "차이", "ˈdɪf.ɚ.əns", "Know the difference between words.", "단어들 사이의 차이를 알아라."),
            ("difficult", "어려운", "ˈdɪf.ə.kəlt", "This word is difficult to remember.", "이 단어는 기억하기 어렵다."),
            ("discover", "발견하다", "dɪˈskʌv.ɚ", "Discover new vocabulary.", "새로운 어휘를 발견해라."),
            ("education", "교육", "ˌedʒ.əˈkeɪ.ʃən", "Education helps people grow.", "교육은 사람들이 성장하도록 돕는다."),
            ("effective", "효과적인", "əˈfek.tɪv", "Repeated review is effective.", "반복 복습은 효과적이다."),
            ("effort", "노력", "ˈef.ɚt", "Effort makes learning easier.", "노력은 학습을 더 쉽게 만든다."),
            ("encourage", "격려하다", "ɪnˈkɝː.ɪdʒ", "Teachers encourage students.", "선생님들은 학생들을 격려한다."),
            ("environment", "환경", "ɪnˈvaɪ.rən.mənt", "The simulator is the test environment.", "시뮬레이터는 테스트 환경이다."),
            ("essential", "필수적인", "ɪˈsen.ʃəl", "Practice is essential for learning.", "연습은 학습에 필수적이다."),
            ("evidence", "증거", "ˈev.ə.dəns", "The result screen shows evidence.", "결과 화면은 증거를 보여 준다."),
            ("experience", "경험", "ɪkˈspɪr.i.əns", "A simple UI improves the experience.", "간단한 UI는 경험을 향상시킨다."),
            ("explain", "설명하다", "ɪkˈspleɪn", "The example explains the meaning.", "예문은 뜻을 설명한다."),
            ("familiar", "익숙한", "fəˈmɪl.jɚ", "Swipe gestures feel familiar.", "스와이프 동작은 익숙하게 느껴진다."),
            ("feature", "기능", "ˈfiː.tʃɚ", "Search is a useful feature.", "검색은 유용한 기능이다."),
            ("focus", "집중하다", "ˈfoʊ.kəs", "Focus on one card at a time.", "한 번에 카드 하나에 집중해라."),
            ("foreign", "외국의", "ˈfɔːr.ən", "English is a foreign language.", "영어는 외국어이다."),
            ("frequent", "빈번한", "ˈfriː.kwənt", "Frequent review builds memory.", "잦은 복습은 기억을 만든다."),
            ("generate", "생성하다", "ˈdʒen.ə.reɪt", "The app generates a study session.", "앱은 학습 세션을 생성한다."),
            ("habit", "습관", "ˈhæb.ɪt", "Daily study becomes a habit.", "매일 공부하면 습관이 된다."),
            ("improve", "향상시키다", "ɪmˈpruːv", "Practice improves vocabulary.", "연습은 어휘력을 향상시킨다."),
            ("include", "포함하다", "ɪnˈkluːd", "Each card includes an example.", "각 카드는 예문을 포함한다."),
            ("increase", "증가하다", "ɪnˈkriːs", "Your score can increase.", "점수는 올라갈 수 있다."),
            ("indicate", "나타내다", "ˈɪn.də.keɪt", "The label indicates progress.", "라벨은 진행 상황을 나타낸다."),
            ("information", "정보", "ˌɪn.fɚˈmeɪ.ʃən", "Tap the card for more information.", "더 많은 정보를 보려면 카드를 눌러라."),
            ("instead", "대신에", "ɪnˈsted", "Use a button instead of swiping.", "스와이프 대신 버튼을 사용해라."),
            ("interest", "관심", "ˈɪn.trəst", "Interest makes study enjoyable.", "관심은 공부를 즐겁게 만든다."),
            ("knowledge", "지식", "ˈnɑː.lɪdʒ", "Vocabulary is useful knowledge.", "어휘는 유용한 지식이다."),
            ("language", "언어", "ˈlæŋ.ɡwɪdʒ", "Language learning takes time.", "언어 학습에는 시간이 걸린다."),
            ("maintain", "유지하다", "meɪnˈteɪn", "Maintain a steady study rhythm.", "꾸준한 학습 리듬을 유지해라."),
            ("memory", "기억", "ˈmem.ɚ.i", "Review supports memory.", "복습은 기억을 돕는다."),
            ("method", "방법", "ˈmeθ.əd", "Swipe study is one method.", "스와이프 학습은 하나의 방법이다."),
            ("necessary", "필요한", "ˈnes.ə.ser.i", "Review is necessary for hard words.", "어려운 단어에는 복습이 필요하다."),
            ("notice", "알아차리다", "ˈnoʊ.t̬ɪs", "Notice the progress number.", "진행 숫자를 알아차려라."),
            ("object", "물건, 대상", "ˈɑːb.dʒekt", "A word card is a screen object.", "단어 카드는 화면의 대상이다."),
            ("opinion", "의견", "əˈpɪn.jən", "Share your opinion in class.", "수업에서 네 의견을 공유해라."),
            ("organize", "정리하다", "ˈɔːr.ɡən.aɪz", "Organize words in a table view.", "테이블 뷰에서 단어를 정리해라."),
            ("participate", "참여하다", "pɑːrˈtɪs.ə.peɪt", "Participate in the quiz.", "퀴즈에 참여해라."),
            ("perform", "수행하다", "pɚˈfɔːrm", "Perform the swipe gesture.", "스와이프 동작을 수행해라."),
            ("practice", "연습하다", "ˈpræk.tɪs", "Practice every day.", "매일 연습해라."),
            ("prepare", "준비하다", "prɪˈper", "Prepare words before studying.", "공부하기 전에 단어를 준비해라."),
            ("prevent", "막다", "prɪˈvent", "Review prevents forgetting.", "복습은 잊어버리는 것을 막는다."),
            ("process", "과정", "ˈprɑː.ses", "Learning is a repeated process.", "학습은 반복되는 과정이다."),
            ("provide", "제공하다", "prəˈvaɪd", "The app provides sample words.", "앱은 샘플 단어를 제공한다."),
            ("purpose", "목적", "ˈpɝː.pəs", "The purpose is word memorization.", "목적은 단어 암기이다."),
            ("quality", "품질", "ˈkwɑː.lə.t̬i", "Clear layout improves quality.", "명확한 배치는 품질을 높인다."),
            ("realize", "깨닫다", "ˈriː.ə.laɪz", "You may realize what you forgot.", "무엇을 잊었는지 깨달을 수 있다."),
            ("reason", "이유", "ˈriː.zən", "There is a reason for review.", "복습에는 이유가 있다."),
            ("receive", "받다", "rɪˈsiːv", "Receive feedback from the quiz.", "퀴즈에서 피드백을 받아라."),
            ("recognize", "인식하다", "ˈrek.əɡ.naɪz", "Recognize the word quickly.", "단어를 빠르게 인식해라."),
            ("reduce", "줄이다", "rɪˈduːs", "Repeated study reduces mistakes.", "반복 학습은 실수를 줄인다."),
            ("remember", "기억하다", "rɪˈmem.bɚ", "Remember the meaning.", "뜻을 기억해라."),
            ("require", "요구하다", "rɪˈkwaɪr", "Some words require more practice.", "어떤 단어들은 더 많은 연습을 요구한다."),
            ("result", "결과", "rɪˈzʌlt", "Check the result after studying.", "공부한 뒤 결과를 확인해라."),
            ("review", "복습하다", "rɪˈvjuː", "Review the words you missed.", "놓친 단어들을 복습해라."),
            ("select", "선택하다", "səˈlekt", "Select an answer in the quiz.", "퀴즈에서 답을 선택해라."),
            ("simple", "간단한", "ˈsɪm.pəl", "The app uses a simple design.", "앱은 간단한 디자인을 사용한다."),
            ("solution", "해결책", "səˈluː.ʃən", "Find a solution to mistakes.", "실수에 대한 해결책을 찾아라."),
            ("support", "지원하다", "səˈpɔːrt", "Buttons support swipe actions.", "버튼은 스와이프 동작을 지원한다."),
            ("system", "시스템", "ˈsɪs.təm", "The system stores study state.", "시스템은 학습 상태를 저장한다."),
            ("transfer", "옮기다", "trænsˈfɝː", "Transfer weak words back to the queue.", "약한 단어를 다시 대기열로 옮겨라."),
            ("useful", "유용한", "ˈjuːs.fəl", "Examples are useful for memory.", "예문은 기억에 유용하다."),
            ("various", "다양한", "ˈver.i.əs", "Various words are included.", "다양한 단어들이 포함되어 있다."),
            ("visible", "보이는", "ˈvɪz.ə.bəl", "Make progress visible.", "진행 상황을 보이게 만들어라."),
            ("wonder", "궁금해하다", "ˈwʌn.dɚ", "I wonder what this word means.", "나는 이 단어가 무슨 뜻인지 궁금하다."),
            ("accurate", "정확한", "ˈæk.jɚ.ət", "Choose the accurate meaning.", "정확한 뜻을 골라라."),
            ("analyze", "분석하다", "ˈæn.əl.aɪz", "Analyze your wrong answers.", "틀린 답을 분석해라."),
            ("approach", "접근법", "əˈproʊtʃ", "This is a new approach to study.", "이것은 공부에 대한 새로운 접근법이다."),
            ("confident", "자신 있는", "ˈkɑːn.fə.dənt", "Be confident when you know a word.", "단어를 알 때는 자신 있게 해라."),
            ("efficient", "효율적인", "ɪˈfɪʃ.ənt", "Short sessions can be efficient.", "짧은 세션은 효율적일 수 있다."),
            ("flexible", "유연한", "ˈflek.sə.bəl", "A flexible queue helps review.", "유연한 대기열은 복습을 돕는다."),
            ("gesture", "동작, 제스처", "ˈdʒes.tʃɚ", "Swipe is the main gesture.", "스와이프가 주요 동작이다."),
            ("progress", "진행", "ˈprɑː.ɡres", "Progress appears at the top.", "진행 상황은 위쪽에 나타난다."),
            ("session", "학습 회차", "ˈseʃ.ən", "Finish one session at a time.", "한 번에 한 세션씩 끝내라.")
        ]

        return entries.map {
            Word(term: $0.0, meaning: $0.1, reading: $0.2, example: $0.3, exampleMeaning: $0.4, state: .new)
        }
    }
}
