import Foundation

extension WordStore {
    static func sampleWords() -> [Word] {
        let entries: [(String, String, String, String)] = [
            ("abandon", "버리다, 포기하다", "어밴던", "Do not abandon your plan too early."),
            ("ability", "능력", "어빌리티", "She has the ability to solve problems."),
            ("accept", "받아들이다", "억셉트", "Please accept my apology."),
            ("achieve", "달성하다", "어치브", "You can achieve your goal with practice."),
            ("active", "활동적인", "액티브", "He is active in the school club."),
            ("adapt", "적응하다", "어댑트", "Students adapt to new classes quickly."),
            ("advice", "조언", "어드바이스", "My teacher gave me useful advice."),
            ("affect", "영향을 미치다", "어펙트", "Weather can affect your mood."),
            ("agree", "동의하다", "어그리", "I agree with your opinion."),
            ("allow", "허락하다", "얼라우", "The app allows users to study words."),
            ("ancient", "고대의", "에인션트", "We learned about ancient history."),
            ("appear", "나타나다", "어피어", "A message will appear on the screen."),
            ("arrive", "도착하다", "어라이브", "They arrive at school at eight."),
            ("article", "기사, 물품", "아티클", "I read an article about technology."),
            ("attention", "주의, 관심", "어텐션", "Pay attention to the card."),
            ("available", "이용 가능한", "어베일러블", "The file is available offline."),
            ("balance", "균형", "밸런스", "Good habits create balance."),
            ("behavior", "행동", "비헤이비어", "The button changes its behavior."),
            ("benefit", "이익, 혜택", "베네핏", "Review has a learning benefit."),
            ("borrow", "빌리다", "바로우", "Can I borrow your notebook?"),
            ("brief", "짧은", "브리프", "Write a brief sentence."),
            ("career", "직업, 경력", "커리어", "She wants a career in design."),
            ("challenge", "도전", "챌린지", "This project is a good challenge."),
            ("choice", "선택", "초이스", "You have a choice in the quiz."),
            ("common", "흔한, 공통의", "커먼", "This is a common English word."),
            ("compare", "비교하다", "컴페어", "Compare the answer with the meaning."),
            ("complete", "완료하다", "컴플리트", "Complete the study session."),
            ("connect", "연결하다", "커넥트", "Connect the word and the meaning."),
            ("consider", "고려하다", "컨시더", "Consider the example sentence."),
            ("continue", "계속하다", "컨티뉴", "Continue until all cards are done."),
            ("create", "만들다", "크리에이트", "Create a simple word list."),
            ("culture", "문화", "컬처", "Language and culture are connected."),
            ("decide", "결정하다", "디사이드", "Decide if you memorized the word."),
            ("describe", "묘사하다", "디스크라이브", "Describe the word in your own words."),
            ("develop", "개발하다", "디벨롭", "We develop an iOS app."),
            ("difference", "차이", "디퍼런스", "Know the difference between words."),
            ("difficult", "어려운", "디피컬트", "This word is difficult to remember."),
            ("discover", "발견하다", "디스커버", "Discover new vocabulary."),
            ("education", "교육", "에듀케이션", "Education helps people grow."),
            ("effective", "효과적인", "이펙티브", "Repeated review is effective."),
            ("effort", "노력", "에퍼트", "Effort makes learning easier."),
            ("encourage", "격려하다", "인커리지", "Teachers encourage students."),
            ("environment", "환경", "인바이런먼트", "The simulator is the test environment."),
            ("essential", "필수적인", "이센셜", "Practice is essential for learning."),
            ("evidence", "증거", "에비던스", "The result screen shows evidence."),
            ("experience", "경험", "익스피리언스", "A simple UI improves the experience."),
            ("explain", "설명하다", "익스플레인", "The example explains the meaning."),
            ("familiar", "익숙한", "퍼밀리어", "Swipe gestures feel familiar."),
            ("feature", "기능", "피처", "Search is a useful feature."),
            ("focus", "집중하다", "포커스", "Focus on one card at a time."),
            ("foreign", "외국의", "포린", "English is a foreign language."),
            ("frequent", "빈번한", "프리퀀트", "Frequent review builds memory."),
            ("generate", "생성하다", "제너레이트", "The app generates a study session."),
            ("habit", "습관", "해빗", "Daily study becomes a habit."),
            ("improve", "향상시키다", "임프루브", "Practice improves vocabulary."),
            ("include", "포함하다", "인클루드", "Each card includes an example."),
            ("increase", "증가하다", "인크리스", "Your score can increase."),
            ("indicate", "나타내다", "인디케이트", "The label indicates progress."),
            ("information", "정보", "인포메이션", "Tap the card for more information."),
            ("instead", "대신에", "인스테드", "Use a button instead of swiping."),
            ("interest", "관심", "인터레스트", "Interest makes study enjoyable."),
            ("knowledge", "지식", "날리지", "Vocabulary is useful knowledge."),
            ("language", "언어", "랭귀지", "Language learning takes time."),
            ("maintain", "유지하다", "메인테인", "Maintain a steady study rhythm."),
            ("memory", "기억", "메모리", "Review supports memory."),
            ("method", "방법", "메서드", "Swipe study is one method."),
            ("necessary", "필요한", "네세서리", "Review is necessary for hard words."),
            ("notice", "알아차리다", "노티스", "Notice the progress number."),
            ("object", "물건, 대상", "오브젝트", "A word card is a screen object."),
            ("opinion", "의견", "어피니언", "Share your opinion in class."),
            ("organize", "정리하다", "오거나이즈", "Organize words in a table view."),
            ("participate", "참여하다", "파티시페이트", "Participate in the quiz."),
            ("perform", "수행하다", "퍼폼", "Perform the swipe gesture."),
            ("practice", "연습하다", "프랙티스", "Practice every day."),
            ("prepare", "준비하다", "프리페어", "Prepare words before studying."),
            ("prevent", "막다", "프리벤트", "Review prevents forgetting."),
            ("process", "과정", "프로세스", "Learning is a repeated process."),
            ("provide", "제공하다", "프로바이드", "The app provides sample words."),
            ("purpose", "목적", "퍼퍼스", "The purpose is word memorization."),
            ("quality", "품질", "퀄리티", "Clear layout improves quality."),
            ("realize", "깨닫다", "리얼라이즈", "You may realize what you forgot."),
            ("reason", "이유", "리즌", "There is a reason for review."),
            ("receive", "받다", "리시브", "Receive feedback from the quiz."),
            ("recognize", "인식하다", "레커그나이즈", "Recognize the word quickly."),
            ("reduce", "줄이다", "리듀스", "Repeated study reduces mistakes."),
            ("remember", "기억하다", "리멤버", "Remember the meaning."),
            ("require", "요구하다", "리콰이어", "Some words require more practice."),
            ("result", "결과", "리절트", "Check the result after studying."),
            ("review", "복습하다", "리뷰", "Review the words you missed."),
            ("select", "선택하다", "셀렉트", "Select an answer in the quiz."),
            ("simple", "간단한", "심플", "The app uses a simple design."),
            ("solution", "해결책", "솔루션", "Find a solution to mistakes."),
            ("support", "지원하다", "서포트", "Buttons support swipe actions."),
            ("system", "시스템", "시스템", "The system stores study state."),
            ("transfer", "옮기다", "트랜스퍼", "Transfer weak words back to the queue."),
            ("useful", "유용한", "유스풀", "Examples are useful for memory."),
            ("various", "다양한", "베리어스", "Various words are included."),
            ("visible", "보이는", "비저블", "Make progress visible."),
            ("wonder", "궁금해하다", "원더", "I wonder what this word means."),
            ("accurate", "정확한", "애큐릿", "Choose the accurate meaning."),
            ("analyze", "분석하다", "애널라이즈", "Analyze your wrong answers."),
            ("approach", "접근법", "어프로치", "This is a new approach to study."),
            ("confident", "자신 있는", "컨피던트", "Be confident when you know a word."),
            ("efficient", "효율적인", "이피션트", "Short sessions can be efficient."),
            ("flexible", "유연한", "플렉서블", "A flexible queue helps review."),
            ("gesture", "동작, 제스처", "제스처", "Swipe is the main gesture."),
            ("progress", "진행", "프로그레스", "Progress appears at the top."),
            ("session", "학습 회차", "세션", "Finish one session at a time.")
        ]

        return entries.map { Word(term: $0.0, meaning: $0.1, reading: $0.2, example: $0.3, state: .new) }
    }
}
